package com.mycompany.motorph;

public enum Roles {
    CHIEF_EXECUTIVE_OFFICER,
    CHIEF_OPERATING_OFFICER,
    CHIEF_FINANCE_OFFICER,
    CHIEF_MARKETING_OFFICER,
    IT_OPERATIONS_SYSTEMS,
    HR_MANAGER,
    HR_TEAM_LEADER,
    HR_RANK_FILE,
    ACCOUNTING_HEAD,
    PAYROLL_MANAGER,
    PAYROLL_TEAM_LEADER,
    PAYROLL_RANK_FILE,
    ACCOUNT_MANAGER,
    ACCOUNT_TEAM_LEADER,
    ACCOUNT_RANK_FILE,
    SALES_MARKETING,
    SUPPLY_CHAIN_LOGISTICS,
    CUSTOMER_SERVICE,
}

